### ISSUE TITLE
Plugin Check Error

### ISSUE THREAD

**Issue by blariviere** [c-kr/check_json#11]
Hi,

Just wondering if there was an issue w/ using zeros as a warning and critical threshold. if I set that it comes back at critical even though the status is a one. if I set the warn and crit to something other than zeros it returns OK.

Check JSON status API CRITICAL - health: 1 | health=1;0;0
Check JSON status API OK - health: 1 | health=1;5;10

Thanks.

**Comment by c-kr** [comment]
This is correct according to the nagios plugin guidelines. 

Warning / Critical 0 means: Generate warning if returned value is < 0 or > 0. 

You could use @0:0 as threshold if you want to alert if value is 0. See https://nagios-plugins.org/doc/guidelines.html

**Comment by blariviere** [comment]
Awesome, thank you for the quick response, works fine now!
