### ISSUE TITLE
Howto handle authentication

### ISSUE THREAD

**Issue by dangul** [c-kr/check_json#17]
Hi, how to use basic authentication using check_json ? Is that supported ?

//Daniel

**Comment by c-kr** [comment]
Hi,

strange, I never tried it. Thought maybe it would work within the url. 

Or you could try to add this to line 109 with your credentials:

    $ua->credentials("www.example.com:80", "Some Realm", "foo", "secret");

http://search.cpan.org/dist/libwww-perl/lib/LWP/UserAgent.pm
http://www.perlfect.com/freescripts/search/list/2002-November/001566.html

Let me know if this works, so I can add this to a new version

**Comment by DennisHoy** [comment]
Hi Christopher
I have the same Issue. It would be very useful if it were possible to give the credentials as parameters to the plugin.
I am not sure how to use your example above. Is the host:port in the first parameter supposed to be then host you check? Can you use localhost if the resource you are checking resides on the same host as Icinga?

**Comment by mib4fun** [comment]
hi,

i've found it ! This as simple as that : 
https://USER:PASSWORD@URL

:smile:
