### ISSUE TITLE
Global symbol "@host" requires explicit package name

### ISSUE THREAD

**Issue by emilv** [c-kr/check_json#19]
I get this error message in the latest version:

> Possible unintended interpolation of @host in string at /usr/lib/nagios/plugins/check_json line 12. Global symbol "@host" requires explicit package name at /usr/lib/nagios/plugins/check_json line 12.
Execution of /usr/lib/nagios/plugins/check_json aborted due to compilation errors.

This is on a fully update Debian Stable with Perl 5.20.2

**Comment by emilv** [comment]
Apparently this comes from the double quotes used for the first line of the usage message. Perl interprets variables inside double-quote strings, so that line should be changed to single quotes.

**Comment by emilv** [comment]
I believe this problem is also solved by escaping the @ as in https://github.com/c-kr/check_json/pull/18

**Comment by c-kr** [comment]
Thanks, pr from #18 merged.
