### ISSUE TITLE
check_value_str change breaking

### ISSUE THREAD

**Issue by senorsmile** [c-kr/check_json#21]
this commit seems to have broken my setup: 

https://github.com/c-kr/check_json/commit/f3233fb247099a6072397f13c007f22a9aa00826

I'm not quite seeing what the intention is here.  Should the warning and critical be specific differently now? 

E.g. 
./check_json.pl -u 'https://myurl/status/healthcheck/version.json' -a '{version}->{message}' -w 292 -c 290 -v

yields: 
$VAR1 = '$check_value = $json_response->{\'{version}->{message}\'}';
Check JSON status API UNKNOWN - No value received

That output of Dumper: '$check_value = $json_response->{\'{version}->{message}\'}'
certainly doesn't make any sense to me either.

**Comment by k-wall** [comment]
I agree with sensorsmile's observation.  https://github.com/c-kr/check_json/commit/f3233fb247099a6072397f13c007f22a9aa00826  has changed the meaning of --attribute.  It means you can no longer traverse a structured object.  The README.md and the program's usage information is now inconsistent with the implementation.

What was the reason behind the change?  It seems to me a useful feature has been lost.

**Comment by c-kr** [comment]
Thanks for clarification, commit f3233fb was reverted
