### ISSUE TITLE
Can't locate Nagios/Plugin.pm in @INC

### ISSUE THREAD

**Issue by wj2369** [c-kr/check_json#25]
I tried to execute the plugin but got error as following, just went through the net but with no luck, can anyone give any suggestion?

[root@nagioscore4 check_json-master]# ./check_json.pl -u https://store.ceair.com/mas/sdk10098/public/ydkbwszb/checkCode2
Can't locate Nagios/Plugin.pm in @INC (@INC contains: /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./check_json.pl line 8.
BEGIN failed--compilation aborted at ./check_json.pl line 8.

I didn't modified anything in the plugin "check_json.pl", if anything should be amended inside? thank you!

**Comment by c-kr** [comment]
You need to install the perl module Nagios::Plugin (using CPAN or your distros packet manager. Debians package name is libnagios-plugin-perl)

**Comment by bornakke** [comment]
Libnagios-plugin-perl is not avaible in last ubuntu. Seem to have been replaced by Monitor:: pluing (https://metacpan.org/pod/Nagios::Plugin), but I have very limited knowledge on perl so it is difficult to understand the consequences. Any suggestions?

**Comment by bunnybravoo** [comment]
thats why its not working in centos new distribution also . so what is the solution for the  new version of pl scripts
......
